// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxpzmbgslbquzdsutxhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4cHptYmdzbGJxdXpkc3V0eGh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjI3NzcsImV4cCI6MjA2NTMzODc3N30.HG5Y-nyqnf_gDZ1vu1y5vFcJQEiNPSQxyBJE6yJiaOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);